import { data } from "./db/data";
import Home from "./pages/Home";
import Header from "./components/Header/Header";
import Banner from "./components/Banner/Banner";
import Footer from "./components/Footer/Footer";
import Menu from "./components/Menu/Menu";
import NewDrops from "./components/NewDrops/NewDrops";
import Card from "./components/Card/Card";
import Products from "./pages/Products/Products";
import InstagramIcon from "@mui/icons-material/Instagram";
import FacebookIcon from "@mui/icons-material/Facebook";
import XIcon from "@mui/icons-material/X";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
export { InstagramIcon, FacebookIcon, LinkedInIcon, XIcon };
export { data, Home, Header, Banner, Footer, Menu, NewDrops, Card, Products };
